- hosts:
  become: yes
  roles:
    - role: node-exporter
      node_exporter_web_listen_address: "0.0.0.0:16100"
      node_exporter_enabled_collectors:
        - systemd
        - textfile:
            directory: "{{ node_exporter_textfile_dir }}"
        - filesystem:
            ignored-mount-points: "^/(sys|proc|dev)($|/)"
            ignored-fs-types: "^(sys|proc|auto)fs$"
        - buddyinfo
        - drbd
        - interrupts
        - ksmd
        - logind
        - meminfo_numa
        - mountstats
        - ntp
        - qdisc
        - runit
        - supervisord
        - tcpstat
  post_tasks:
    - name: Expose service port
      firewalld:
        immediate: yes
        port: 16100/tcp
        permanent: true
        state: enabled
