- hosts:
  become: yes
  tasks:
    #- name: install necessary packages
    #  yum:
    #    name:
    #      - net-tools
    #      - zip
    #      - unzip
    #      - bzip2
    #      - tree
    #      - psmisc
    #      - wget
    #      - gcc
    #      - gcc-c++
    #      - openssl
    #      - openssl-devel
    #      - zlib
    #      - zlib-devel
    #      - sysstat
    #      - centos-release-gluster
    #    state: latest
    #- name: install glusterfs
    #  yum:
    #    name:
    #      - glusterfs
    #      - glusterfs-fuse
    #    state: latest
    - name: set hosts
      blockinfile:
        path: /etc/hosts
        block: |
          219.76.4.4 github-cloud.s3.amazonaws.com
          52.216.16.16 github-production-release-asset-2e65be.s3.amazonaws.com
          10.10.80.64 bslsvrpingpoint
    - name: set history format
      blockinfile:
        path: /etc/bashrc
        block: |
          HISTTIMEFORMAT="%Y-%m-%d_%H:%M:%S"
          export HISTTIMEFORMAT
      notify:
        - enable bash configuration
    - name: set limits
      blockinfile:
        path: /etc/security/limits.conf
        block: |
          * soft nofile 65535
          * soft nproc 65535
          * hard nofile 65535
          * hard nproc 65535
          * soft nofile 65535
          root soft nofile unlimited
    - name: set ssh MaxAuthTries
      lineinfile:
        dest: /etc/ssh/sshd_config
        regexp: '^#MaxAuthTries'
        line: 'MaxAuthTries 5'
        backrefs: yes
      notify:
        - restart sshd
    - name: set ssh LoginGraceTime
      lineinfile:
        dest: /etc/ssh/sshd_config
        regexp: '^#LoginGraceTime'
        line: 'LoginGraceTime 2m'
        backrefs: yes
      notify:
        - restart sshd
    - name: set ssh LogLevel
      lineinfile:
        dest: /etc/ssh/sshd_config
        regexp: '^#LogLevel'
        line: 'LogLevel INFO'
        backrefs: yes
      notify:
        - restart sshd
    - name: disable empty password
      lineinfile:
        dest: /etc/ssh/sshd_config
        regexp: '^#UseDNS yes'
        line: 'UseDNS no'
        backrefs: yes
      notify:
        - restart sshd
    - name: disable GSSAPIAuthentication
      lineinfile:
        dest: /etc/ssh/sshd_config
        regexp: '^GSSAPIAuthentication yes'
        line: 'GSSAPIAuthentication no'
        backrefs: yes
      notify:
        - restart sshd
    - name: set net.core.netdev_max_backlog
      sysctl:
        name: net.core.netdev_max_backlog
        value: 16384
    - name: set net.core.rmem_default
      sysctl:
        name: net.core.rmem_default
        value: 6291456
    - name: set net.core.rmem_max
      sysctl:
        name: net.core.rmem_max
        value: 12582912
    - name: set net.core.somaxconn
      sysctl:
        name: net.core.somaxconn
        value: 262114
    - name: set net.core.wmem_default
      sysctl:
        name: net.core.wmem_default
        value: 6291456
    - name: set net.core.wmem_max
      sysctl:
        name: net.core.wmem_max
        value: 12582912
    - name: set net.ipv4.ip_local_port_range
      sysctl:
        name: net.ipv4.ip_local_port_range
        value: 1024 65000
    - name: set net.ipv4.tcp_fin_timeout
      sysctl:
        name: net.ipv4.tcp_fin_timeout
        value: 30
    - name: set net.ipv4.tcp_keepalive_intvl
      sysctl:
        name: net.ipv4.tcp_keepalive_intvl
        value: 15
    - name: set net.ipv4.tcp_keepalive_time
      sysctl:
        name: net.ipv4.tcp_keepalive_time
        value: 600
    - name: set net.ipv4.tcp_max_orphans
      sysctl:
        name: net.ipv4.tcp_max_orphans
        value: 32768
    - name: set net.ipv4.tcp_max_syn_backlog
      sysctl:
        name: net.ipv4.tcp_max_syn_backlog
        value: 16384
    - name: set net.ipv4.tcp_max_tw_buckets
      sysctl:
        name: net.ipv4.tcp_max_tw_buckets
        value: 36000
    - name: set net.ipv4.tcp_rmem
      sysctl:
        name: net.ipv4.tcp_rmem
        value: 10240 87380 12582912
    - name: set net.ipv4.tcp_syncookies
      sysctl:
        name: net.ipv4.tcp_syncookies
        value: 1
    - name: set net.ipv4.tcp_tw_recycle
      sysctl:
        name: net.ipv4.tcp_tw_recycle
        value: 1
    - name: set net.ipv4.tcp_tw_reuse
      sysctl:
        name: net.ipv4.tcp_tw_reuse
        value: 1
    - name: set net.ipv4.tcp_wmem
      sysctl:
        name: net.ipv4.tcp_wmem
        value: 10240 87380 12582912
    #- name: set multi-user.target
    #  command: systemctl set-default multi-user.target
  handlers:
    - name: restart sshd
      service:
        name: sshd
        state: restarted
    - name: enable bash configuration
      command: bash /etc/bashrc
